// 分类 ++
{
  "name": "奈落影院",
  "url": "https://newfii.com",
  "tihuan": "cnzz.com",
  "User": "空",
  "shouye": "1",
  
  //"fenlei": "电影片库$/index.php/vod/show/id/1/page/#剧集片库$/index.php/vod/show/id/2/page/#动漫片库$/index.php/vod/show/id/3/page/#综艺片库$/index.php/vod/show/id/4/page/#B站片库$/index.php/vod/show/id/34/page/#记录片库$/index.php/vod/show/id/27/page/#4K专区片库$/index.php/vod/show/id/33/page/",
  "fenlei": "电影$/index.php/vod/show/id/1/page/#国产剧$/index.php/vod/show/id/13/page/#日韩剧$/index.php/vod/show/id/15/page/#欧美剧$/index.php/vod/show/id/16/page/#港台剧$/index.php/vod/show/id/14/page/#海外剧$/index.php/vod/show/id/21/page/#童漫$/index.php/vod/show/id/24/page/#动画片$/index.php/vod/show/id/20/page/#国漫$/index.php/vod/show/id/22/page/#日漫$/index.php/vod/show/id/25/page/#欧漫$/index.php/vod/show/id/23/page/#综艺$/index.php/vod/show/id/4/page/#番剧(B站)$/index.php/vod/show/id/35/page/#国创(B站)$/index.php/vod/show/id/36/page/#记录片$/index.php/vod/show/id/27/page/#科幻片$/index.php/vod/show/id/6/page/#动作片$/index.php/vod/show/id/7/page/#喜剧片$/index.php/vod/show/id/8/page/#爱情片$/index.php/vod/show/id/9/page/#恐怖片$/index.php/vod/show/id/10/page/#剧情片$/index.php/vod/show/id/11/page/#战争片$/index.php/vod/show/id/12/page/",
  "houzhui": ".html",
  
  "shifouercijiequ": "0",
  "jiequqian": "空",
  "jiequhou": "空",
  "jiequshuzuqian": "class=\"module-item-pic\"",
  "jiequshuzuhou": "</div>",
  "tupianqian": "data-src=\"",
  "tupianhou": "\"",
  "biaotiqian": "title=\"",
  "biaotihou": "\"",
  "lianjieqian": "href=\"",
  "lianjiehou": "\"",
  
  "sousuoqian": "/index.php/ajax/suggest?mid=1&wd=",
  "sousuohou": "&limit=500",
  "sousuohouzhui": "/index.php/vod/detail/id/",
  "ssmoshi": "0",
  "sousuoshifouercijiequ": "0",
  "jspic": "pic",
  "jsname": "name",
  "jsid": "id",
  "ssjiequqian": "空",
  "ssjiequhou": "空",
  "ssjiequshuzuqian": "空",
  "ssjiequshuzuhou": "空",
  "sstupianqian": "空",
  "sstupianhou": "空",
  "ssbiaotiqian": "空",
  "ssbiaotihou": "空",
  "sslianjieqian": "空",
  "sslianjiehou": "空",
  
  "bfshifouercijiequ": "0",
  "bfjiequqian": "空",
  "bfjiequhou": "空",
  "bfjiequshuzuqian": "id=\"sort-item",
  "bfjiequshuzuhou": "</div>",
  
  "zhuangtaiqian": "集数：</span>",
  "zhuangtaihou": "</div>",
  "daoyanqian": "导演：</span>",
  "daoyanhou": "</div>",
  "zhuyanqian": "主演：</span>",
  "zhuyanhou": "</div>",
  "juqingqian": "剧情：</span>",
  "juqinghou": "</div>",
  
  "bfyshifouercijiequ": "0",
  "bfyjiequqian": "空",
  "bfyjiequhou": "空",
  "bfyjiequshuzuqian": "<a",
  "bfyjiequshuzuhou": "/a>",
  "bfbiaotiqian": "<span>",
  "bfbiaotihou": "<",
  "bflianjieqian": "href=\"",
  "bflianjiehou": "\""
}
