{
 "ua": "",
 "homeUrl": "http://www.niumatv.com",
     "dcVipFlag": "true",
  "pCfgJs": "http://www.niumatv.com/static/js/playerconfig.js",
  "pCfgJsR": "[\\W|\\S|.]*?MacPlayerConfig.player_list[\\W|\\S|.]*?=([\\W|\\S|.]*?),MacPlayerConfig.downer_list",
  "dcShow2Vip": {},
  "dcPlayUrl": "true",
 "cateNode": "//div[contains(@class, 'nav')]/ul/li/a[contains(@href, 'type')]",
 "cateName": "/@title",
 "cateId": "/@href",
 "cateIdR": "/type/(\\S+).html",
    "cateManual": {      "电影":"dianying",
    "电视剧":"dianshijiu",
    "综艺":"zongyi",
    "动漫":"dongman"}, 
 "homeVodNode": "//div[contains(@class, 'lists-content')]/ul/li/a[contains(@class, 'vodlist__thumb')]",
 "homeVodName": "@title",
 "homeVodId": "@href",
 "homeVodIdR": "/vod/(\\w+).html",
 "homeVodImg": "/@data-original",
 "homeVodMark": "/div[contains(@class,'note')]/span/text()",
 "cateUrl": "http://www.niumatv.com/type/{cateId}-{catePg}.html",
 "cateVodNode": "//div[contains(@class, 'lists-content')]/ul/li/a[contains(@class, 'vodlist__thumb')]",
 "cateVodName": "/@title",
 "cateVodId": "/@href",
 "cateVodIdR": "/vod/(\\w+).html",
 "cateVodImg": "/@data-original",
 "cateVodMark": "/div[contains(@class,'note')]/span/text()",
 "dtUrl": "http://www.niumatv.com/vod/{vid}.html",
  "dtNode": "//body",
  "dtName": "//header[@class='product-header']/img/@alt",
  "dtNameR": "",
  "dtImg": "//header[@class='product-header']/img/@src",
  "dtImgR": "\\S+(http\\S+)",
  "dtCate": "//div[contains(@class, 'product-excerpt') and contains(text(), '分类')]/following-sibling::*/span/a/text()",
  "dtCateR": "",
  "dtYear": "//div[contains(@class, 'product-excerpt') and contains(text(), '年份')]/following-sibling::*/span/a/text()",
  "dtYearR": "",
  "dtArea": "//div[contains(@class, 'product-excerpt') and contains(text(), '地区')]/following-sibling::*/span/a/text()",
  "dtAreaR": "",
  "dtMark": "//div[contains(@class, 'product-excerpt') and contains(text(), '更新')]/following-sibling::*/span/a/text()",
  "dtMarkR": "",
  "dtActor": "//div[contains(@class, 'product-excerpt') and contains(text(), '主演')]/following-sibling::*/span/a/text()",
  "dtActorR": "",
  "dtDirector": "//div[contains(@class, 'product-excerpt') and contains(text(), '导演')]/following-sibling::*/span/a/text()",
  "dtDirectorR": "",
  "dtDesc": "//div[contains(@class, 'product-excerpt') and contains(text(), '简介')]/span/text()",
  "dtDescR": "",
  "dtFromNode": "//div[contains(@class, 'playlists') and contains(@id, 'slider')]//dl/dt",
  "dtFromName": "/text()",
 "dtUrlNode": "//div[contains(@class, 'playlist clearfix')]/ul",
 "dtUrlSubNode": "/li/a",
 "dtUrlId": "/@href",
 "dtUrlIdR": "/play/(\\S+).html",
 "dtUrlName": "/text()",
 "playUrl": "http://www.niumatv.com/play/{playUrl}.html",
 "searchUrl": "http://www.niumatv.com/index.php/ajax/suggest?mid=1&wd={wd}&limit=10",
  "scVodNode": "json:list",
  "scVodName": "name",
  "scVodId": "id",
  "scVodIdR": "",
  "scVodImg": "pic",
  "scVodMark": ""
}
