{
    "author": "春风",
    "ua": "",
    "homeUrl": "https://www.youbotv.cn/",
    "dcVipFlag": "true",
    "pCfgJs": "https://www.youbotv.cn/static/js/playerconfig.js",
    "pCfgJsR": "MacPlayerConfig.player_list=([\\w\\W]*?),MacPlayerConfig.downer_list=",
    "dcShow2Vip": {},
    "dcPlayUrl": "true",
    "cateManual": {
        "电影": "1",
        "连续剧": "2",
        "动漫": "4",
        "综艺": "3"
    },
    "homeVodNode": "//div[@class='module-item']",
    "homeVodName": "//div[@class='module-item-pic']/a/@title",
    "homeVodId": "//div[@class='module-item-pic']/a/@href",
    "homeVodIdR": "/voddetail/(\\w+).html",
    "homeVodImg": "//div[@class='module-item-pic']/img/@data-src",
    "homeVodImgR": "\\S*(http\\S+)",
    "homeVodMark": "//div[@class='module-item-text']/text()",
    "cateUrl": "https://www.youbotv.cn/vodshow/{cateId}--------{catePg}---.html",
    "cateVodNode": "//div[@class='module-item']",
    "cateVodName": "//div[@class='module-item-pic']/a/@title",
    "cateVodId": "//div[@class='module-item-pic']/a/@href",
    "cateVodIdR": "/voddetail/(\\w+).html",
    "cateVodImg": "//div[@class='module-item-pic']/img/@data-src",
    "cateVodImgR": "\\S*(http\\S+)",
    "cateVodMark": "//div[@class='module-item-text']/text()",
    "dtUrl": "https://www.youbotv.cn/voddetail/{vid}.html",
    "dtNode": "//body",
    "dtName": "//h1[@class='page-title']/text()",
    "dtNameR": "",
    "dtImg": "//div[@class='mobile-play']//div[@class='module-item-pic']/img/@data-src",
    "dtImgR": "\\S*(http\\S+)",
    "dtCate": "//div[@class='tag-link']/a/text()",
    "dtCateR": "",
    "dtYear": "//a[@class='tag-link'][2]/text()",
    "dtYearR": "",
    "dtArea": "//a[@class='tag-link'][3]/text()",
    "dtAreaR": "",
    "dtDirector": "//span[contains(text(), '导演')]/following-sibling::/div/a/text()",
    "dtDirectorR": "",
    "dtActor": "//span[contains(text(), '主演')]/following-sibling::/div/a/text()",
    "dtActorR": "",
    "dtDesc": "//span[contains(text(), '剧情')]/following-sibling::/div/span/text()",
    "dtDescR": "",
    "dtFromNode": "//div[@class='module-tab-content']/div/span",
    "dtFromName": "/text()",
    "dtFromNameR": "",
    "dtUrlNode": "//div[@class='module-blocklist']/div",
    "dtUrlSubNode": "/a",
    "dtUrlId": "@href",
    "dtUrlIdR": "/vodplay/(\\S+).html",
    "dtUrlName": "/span/text()",
    "dtUrlNameR": "",
    "playUrl": "https://www.youbotv.cn/vodplay/{playUrl}.html",
    "playUa": "",
    "searchUrl": "https://www.youbotv.cn/vodsearch/-------------.html?wd={wd}",
    "scVodNode": "//div[@class='module-items']",
    "scVodName": "//h3/a/@title",
    "scVodId": "//h3/a/@href",
    "scVodIdR": "/voddetail/(\\w+).html",
    "scVodImg": "//img/@data-src",
    "scVodImgR": "\\S*(http\\S+)",
    "scVodMark": "//a[@class='video-serial']/text()"
}
