{
  "ua": "",
"homeUrl": "https://www.lgyy.cc/",
"dcVipFlag": "true",
"pCfgJs": "https://www.lgyy.cc/static/js/playerconfig.js",
"pCfgJsR": "[\\W|\\S|.]*?MacPlayerConfig.player_list[\\W|\\S|.]*?=([\\W|\\S|.]*?),MacPlayerConfig.downer_list",
"dcShow2Vip": {},
"dcPlayUrl": "true",
  "cateManual": {"电影": "1", "电视剧": "2", "综艺": "3", "动漫": "4"},
  "homeVodNode": "//div[contains(@class, 'module-items')]/a",
  "homeVodName":"/@title",
  "homeVodId": "/@href",
  "homeVodIdR": "/voddetail/(\\S+).html",
  "homeVodImg": "//img[@referrerpolicy='no-referrer' and contains(@class, 'lazy lazyload')]/@data-original",
  "homeVodMark": "",
  "cateUrl": "https://www.lgyy.cc/vodshow/{cateId}--------{catePg}---.html",
  "cateVodNode":  "//div[contains(@class, 'module-items')]/a",
  "cateVodName": "/@title",
  "cateVodId": "/@href",
  "cateVodIdR": "/voddetail/(\\S+).html",
  "cateVodImg": "//img[@referrerpolicy='no-referrer' and contains(@class, 'lazy lazyload')]/@data-original",
  "cateVodMark": "",
  "dtUrl": "https://www.lgyy.cc/voddetail/{vid}.html",
  "dtNode": "//div[contains(@class,'module-main')]/div/div/div/img",
  "dtName": "/@alt",
  "dtImg":"/@data-original",
 "dtFromNode": "//div[contains(@class,'module-tab-items-box hisSwiper')]/div",
 "dtFromName": "//span/text()",

  "dtUrlNode": "//div[contains(@class,'module-play-list-content')]",
  "dtUrlSubNode": "/a",
  "dtUrlId": "@href",
  "dtUrlIdR": "/vodplay/(\\S+).html",
  "dtUrlName": "/span/text()",
  "playUrl": "https://www.lgyy.cc/vodplay/{playUrl}.html",


 "searchUrl": "https://www.lgyy.cc/index.php/ajax/suggest?mid=1&wd={wd}",
  
  "scVodNode": "json:list",
  "scVodName": "name",
  "scVodId": "id",
  "scVodIdR": "",
  "scVodImg": "pic",
  "scVodMark": ""
}
