{
    "author":"baddychen",
	"ua": "",
	"homeUrl": "http://4kan.me/",
    "cateManual": {"电影":"1","剧集":"2","综艺":"3","动漫":"4","日韩":"15","欧美":"16"},
	"homeVodNode": "//ul[@class='stui-vodlist clearfix']//div[@class='stui-vodlist__box']",
	"homeVodName": "/a/span[4]/text()",
	"homeVodId": "/a/@href",
	"homeVodIdR": "/voddetail/(\\w+)/",
	"homeVodImg": "/a/@data-original",
	"homeVodImgR": "\\S+(http\\S+)",
	"homeVodMark": "/a/span[3]/text()",
    "cateUrl": "http://4kan.me/vodshow/{cateId}--------{catePg}---/",
	"cateVodNode": "//ul[@class='stui-vodlist clearfix']//div[@class='stui-vodlist__box']",
	"cateVodName": "/a/span[4]/text()",
	"cateVodId": "/a/@href",
	"cateVodIdR": "/voddetail/(\\w+)/",
	"cateVodImg": "/a/@data-original",
	"cateVodImgR": "\\S+(http\\S+)",
	"cateVodMark": "/a/span[3]/text()",
	"dtUrl": "http://4kan.me/voddetail/{vid}/",
	"dtNode": "//body",
	"dtName": "//div[@class='stui-content__thumb']/a/@title",
	"dtNameR": "",
	"dtImg": "//div[@class='stui-content__thumb']/a/img/@data-original",
	"dtImgR": "",
    "dtCate": "//span[contains(@class,'text-muted') and (contains(text(),'类型'))]/following-sibling::*/text()",
	"dtArea": "//span[contains(@class,'text-muted') and (contains(text(),'地区'))]/following-sibling::*/text()",
	"dtYear": "//span[contains(@class,'text-muted') and (contains(text(),'年份'))]/following-sibling::*/text()",
	"dtDirector": "//span[contains(@class,'text-muted') and (contains(text(),'主演'))]/following-sibling::*/text()",
	"dtActor": "//span[contains(@class,'text-muted') and (contains(text(),'导演'))]/following-sibling::*/text()",
    "dtDesc": "//div[@class='stui-content__detail']/p[5]/text()",
	"dtMark": "", 
	"dtFromNode": "//a[@data-toggle='tab' and (contains(@href,'playlist'))]",
	"dtFromName": "/text()",
	"dtFromNameR": "",
	"dtUrlNode": "//ul[contains(@class,'stui-content__playlist')]",
	"dtUrlSubNode": "/li/a",
	"dtUrlId": "@href",
	"dtUrlIdR": "/vodplay/(\\S+)/",
	"dtUrlName": "/text()",
	"dtUrlNameR": "",
	"playUrl": "http://4kan.me/vodplay/{playUrl}/",
	"playUa": "",
	"searchUrl": "http://4kan.me/index.php/ajax/suggest?mid=1&wd={wd}&limit=50",
	"scVodNode": "json:list",
	"scVodName": "name",
	"scVodId": "id",
	"scVodIdR": "",
	"scVodImg": "pic",
	"scVodMark": "" 
}
