{
"ua": "Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1",

 "homeUrl": "http://www.rr520.cc/",
  "cateManual": {"电影":"1","连续剧": "2","综艺": "3","动漫": "4"},
  "homeVodNode": "//a[contains(@class,'stui-vodlist__thumb lazyload')]",
  "homeVodName":"/@title",
  "homeVodId": "/@href",
  "homeVodIdR": "/vod/(\\w+).html",
  "homeVodImg": "/@data-original",
 "homeVodMark": "",
  "cateUrl": "http://www.rr520.cc/list/{cateId}-{catePg}.html",
  "cateVodNode": "//a[contains(@class, 'stui-vodlist__thumb lazyload')]",
  "cateVodName":"/@title",
  "cateVodId": "/@href",
  "cateVodIdR": "/vod/(\\S+).html",
  "cateVodImg": "/@data-original",
  "cateVodMark":  "",
  "dtUrl": "http://www.rr520.cc/vod/{vid}.html",
  "dtNode": "//div[contains(@class,'stui-content__thumb')]",
  "dtName": "/a/@title",
  "dtImg":"/a/img/@data-original",
 //"dtCate": "//ul[@class='moviedteail_list']/li[contains(text(),'类型')]/a/text()",
 //"dtYear": "//ul[@class='moviedteail_list']/li[contains(text(),'年份')]/a/text()",
 //"dtArea": "//ul[@class='moviedteail_list']/li[contains(text(),'地区')]/a/text()",
 // "dtActor": "//ul[@class='moviedteail_list']/li[contains(text(),'主演')]/a/text()",
 // "dtDirector": "//ul[@class='moviedteail_list']/li[contains(text(),'导演')]/a/text()",
 //"dtFromNode": "//div[contains(@class,'mi_paly_box')]//div[@class='ypxingq_t']",
 //"dtFromName": "/text()",
 "dtFromNode":"//h3[contains(@class,'title')]",
 "dtFromName": "/text()",
  "dtUrlNode": "//div[contains(@class, 'stui-pannel_bd')]//ul[contains(@class, 'stui-content__playlist')]",
  "dtUrlSubNode": "/li/a",
  "dtUrlId": "/@href",
  "dtUrlIdR": "/play/(\\S+).html",
  "dtUrlName": "/text()",
  "playUrl": "http://www.rr520.cc/play/{playUrl}.html",
 "searchUrl":"http://www.rr520.cc/index.php/ajax/suggest?mid=1&wd={wd}&limit=10",
    "scVodNode": "json:list",
    "scVodName": "name",
    "scVodId": "id",
    "scVodIdR": "",
    "scVodImg": "pic",
    "scVodMark": ""
}


