{
    "author":"baddychen",
	"ua": "",
	"homeUrl": "https://ysjdm.net/index.php/vod/show/id/20.html",
	"cateNode": "//div[@id='hl02']/div/ul/li/a[contains(@href,'class')]",
	"cateName": "/text()",
	"cateId": "/@href",
	"cateIdR": "/index.php/vod/show/(\\S+)/id/20.html",
	"cateManual": {},
	"homeVodNode": "//ul[contains(@class,'vodlist_wi')]/li/a",
	"homeVodName": "/@title",
	"homeVodId": "/@href",
	"homeVodIdR": "/index.php/vod/detail/id/(\\w+).html",
	"homeVodImg": "/@data-original",
	"homeVodImgR": "\\S+(http\\S+)",
	"homeVodMark": "/span[contains(@class,'pic_text')]/text()",
	"cateUrl": "https://ysjdm.net/index.php/vod/show/{cateId}/id/20/page/{catePg}.html",
	"cateVodNode": "//ul[contains(@class,'vodlist_wi')]/li/a",
	"cateVodName": "/@title",
	"cateVodId": "/@href",
	"cateVodIdR": "/index.php/vod/detail/id/(\\w+).html",
	"cateVodImg": "/@data-original",
	"cateVodImgR": "\\S+(http\\S+)",
	"cateVodMark": "/span[contains(@class,'pic_text')]/text()",
	"dtUrl": "https://ysjdm.net/index.php/vod/detail/id/{vid}.html",
	"dtNode": "//body",
	"dtName": "//div[@class='content_thumb fl']/a/@title",
	"dtNameR": "",
	"dtImg": "//div[@class='content_thumb fl']/a/@data-original",
	"dtImgR": "\\S+(http\\S+)",
	"dtMark": "",
	"dtMarkR": "",
	"dtActor": "//div[@class='content_detail content_min fl']/ul/li[3]/text()",
	"dtDirector": "//div[@class='content_detail content_min fl']/ul/li[4]/a/text()",
	"dtCate": "//div[@class='content_detail content_min fl']/ul/li[1]/a[3]/text()",
	"dtArea": "//div[@class='content_detail content_min fl']/ul/li[1]/a[2]/text()",
	"dtYear": "//span[contains(@class,'text_muted hidden_xs') and contains(text(), '年份')]/following-sibling::*/text()",
	"dtDesc": "//div[@class='content_desc context clearfix']/span/text()",
	"dtFromNode": "//div[@id='NumTab']/a",
	"dtFromName": "/text()",
	"dtFromNameR": "",
	"dtUrlNode": "//ul[@class='content_playlist clearfix']",
	"dtUrlSubNode": "/li/a",
	"dtUrlId": "/@href",
	"dtUrlIdR": "/index.php/vod/play/id/(\\S+).html",
	"dtUrlName": "/text()",
	"dtUrlNameR": "",
	"playUrl": "https://ysjdm.net/index.php/vod/play/id/{playUrl}.html",
	"playUa": "",
	"searchUrl": "https://ysjdm.net/index.php/ajax/suggest?mid=1&wd={wd}&limit=100",
	"scVodNode": "json:list",
	"scVodName": "name",
	"scVodId": "id",
	"scVodIdR": "",
	"scVodImg": "pic",
	"scVodMark": ""
}
